// lib/models/seat_types.dart

class SeatType {
  final int width;
  final int length;
  final int zIndex;

  const SeatType({
    required this.width,
    required this.length,
    required this.zIndex,
  });
}

const Map<String, SeatType> seatTypes = {
  "SS": SeatType(width: 1, length: 1, zIndex: 0),
  "SL": SeatType(width: 2, length: 2, zIndex: 0),
  "LB": SeatType(width: 2, length: 2, zIndex: 0),
  "UB": SeatType(width: 2, length: 2, zIndex: 1),
  "BS": SeatType(width: 2, length: 2, zIndex: 0),
  "PB": SeatType(width: 1, length: 1, zIndex: 0),
  "NPB": SeatType(width: 1, length: 1, zIndex: 0),
  "SLB": SeatType(width: 2, length: 2, zIndex: 0),
  "SUB": SeatType(width: 2, length: 2, zIndex: 1),
  "SST": SeatType(width: 1, length: 1, zIndex: 0),
  "NA": SeatType(width: 1, length: 1, zIndex: 0),
  "ST": SeatType(width: 1, length: 1, zIndex: 0),
  "DLB": SeatType(width: 2, length: 2, zIndex: 0),
  "DUB": SeatType(width: 2, length: 2, zIndex: 1),
  "WSS": SeatType(width: 2, length: 2, zIndex: 0),
  "WST": SeatType(width: 1, length: 1, zIndex: 0),
  "WLB": SeatType(width: 2, length: 2, zIndex: 0),
  "WUB": SeatType(width: 2, length: 2, zIndex: 1),
  "WSL": SeatType(width: 1, length: 1, zIndex: 0),
  "WSU": SeatType(width: 1, length: 1, zIndex: 1),
  "BU": SeatType(width: 2, length: 2, zIndex: 0),
  "EC": SeatType(width: 1, length: 1, zIndex: 0),
  "SEMI CAMA": SeatType(width: 2, length: 2, zIndex: 0),
  "SALON CAMA": SeatType(width: 2, length: 2, zIndex: 0),
  "CLASICO": SeatType(width: 1, length: 1, zIndex: 0),
  "EJECUTIVO": SeatType(width: 1, length: 1, zIndex: 0),
  "PREMIUM": SeatType(width: 1, length: 1, zIndex: 0),
  "SC": SeatType(width: 2, length: 2, zIndex: 0),
  "CO": SeatType(width: 1, length: 1, zIndex: 0),
  "EX": SeatType(width: 2, length: 2, zIndex: 0),
  "SP": SeatType(width: 1, length: 1, zIndex: 0),
  "SALON": SeatType(width: 1, length: 1, zIndex: 0),
  "SALON MIXTO": SeatType(width: 1, length: 1, zIndex: 0),
  "SEMICAMA": SeatType(width: 2, length: 2, zIndex: 0),
  "CAMA": SeatType(width: 2, length: 2, zIndex: 0),
  "COMUN": SeatType(width: 1, length: 1, zIndex: 0),
  "COMUN CON AIRE": SeatType(width: 1, length: 1, zIndex: 0),
  "SCA": SeatType(width: 2, length: 2, zIndex: 0),
  "SX": SeatType(width: 1, length: 1, zIndex: 0),
  "BLACK": SeatType(width: 1, length: 1, zIndex: 0),
  "PULLMAN": SeatType(width: 1, length: 1, zIndex: 0),
  "CA": SeatType(width: 1, length: 1, zIndex: 0),
  "XP": SeatType(width: 2, length: 2, zIndex: 0),
  "PREMIUM PROMO": SeatType(width: 1, length: 1, zIndex: 0),
  "SALON CAMA PROMO": SeatType(width: 2, length: 2, zIndex: 0),
  "SEMICAMA PROMO": SeatType(width: 2, length: 2, zIndex: 0),
  "CAMA VIP": SeatType(width: 2, length: 2, zIndex: 0),
  "Cama Ejecutivo": SeatType(width: 1, length: 1, zIndex: 0),
  "Cama Suite": SeatType(width: 2, length: 2, zIndex: 0),
  "BJ": SeatType(width: 2, length: 2, zIndex: 0),
  "EJ": SeatType(width: 2, length: 2, zIndex: 0),
  "SU": SeatType(width: 2, length: 2, zIndex: 0),
  "BT": SeatType(width: 2, length: 2, zIndex: 0),
  "SJ": SeatType(width: 2, length: 2, zIndex: 0),
  "LS": SeatType(width: 2, length: 2, zIndex: 0),
  "SUITE CAMA": SeatType(width: 2, length: 2, zIndex: 0),
  "COMPARTIDO": SeatType(width: 2, length: 2, zIndex: 0),
  "EXCLUSIVO": SeatType(width: 2, length: 2, zIndex: 0),
  "SEMI EXCLUSIVO": SeatType(width: 2, length: 2, zIndex: 0),
};
